version: "3.9"

services:

  mongodb:
    image: mongo:7
    container_name: mern-mongodb-5
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network
    ports:
      - "27016:27017"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    image: ${BACKEND_IMAGE}
    container_name: mern-backend-6
    restart: always
    depends_on:
     - mongodb
    env_file:
     - ./backend/.env
    networks:
      - mern-network
    ports:
      - "5000:5000"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
    user: "1000:1000"
    read_only: true

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: mern-frontend-6
    restart: always
    depends_on:
     - backend
    networks:
      - mern-network
    ports:
      - "3000:3000"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
    user: "1000:1000"
    read_only: true

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge
